### ISSUE TITLE
[PENDING] Non-Latin folder crash 

### ISSUE THREAD

**Issue by sergeevabc** [J0113/ProxyHuntr#1]
Windows 7 x64, ProxyHuntr RC2 portable.

Launching ```ProxyHuntr.exe``` as admin from ```C:\Тестирование\ProxyHuntr```, but it crashes immediately.

![](https://images.vfl.ru/ii/1544480651/edfab1b9/24553056.png)

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ProxyHuntr.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5b8e995f
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10240.16390
  Fault Module Timestamp:	55a5b718
  Exception Code:	40000015
  Exception Offset:	0000000000065a5f
```

P.S. Also the app lacks info what kind of proxy it is (HTTP/S/SOCKS4/5) and what its latency is (ms).

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by HiddenMotives** [comment]
> Errr… Hello?

Hi if your not getting a reply take a look at my project and see if it can suit your needs https://github.com/HiddenMotives/ProxyChecker

**Comment by J0113** [comment]
Sorry for the late response, I am not actively working on this project. Try running with administrator right? And are there any logs created?
