### ISSUE TITLE
you can help me ?!

### ISSUE THREAD

**Issue by xurack** [J0113/ProxyHuntr#2]

**Comment by xurack** [comment]
> 
> 
> I am noob in python :(

Hello
You can help me. I want to design a few graphical programs in Python for myself. I wanted to wonder how I can do the software you designed.
Can you help me on this subject?
What is the right way to get in touch with you?
If you can send me an email or send me directly in the telegram messenger software
ilijenab@Gmail.com
telegram : @ilijenab

**Comment by tintupaul** [comment]
Hi,

There are several open source tool-kits for GUI in python. WxPython, PyQT, Tkinter and kivy are some among them. Many tutorials are available online, which can be helpful to you.

Best Regards!!!

**Comment by J0113** [comment]
Like @tintupaul said. There are multiple tools. ProxyHuntr's UI was made with PyQT. PyQT is well documented and should be usable for most projects. Get started with QT here: https://wiki.python.org/moin/PyQt
